---

#1. Installation mariadb et ses extensions Python
- name: "mariadb-server installation"
  apt:
    name: "mariadb-server,python3-mysqldb"
    state: present

#2. Active le service MariaDB
- name: "start mariadb service"
  service:
    name: mariadb
    state: started
    enabled: yes

# Active l'écoute sur tous les ports
- name: "change 50-server.cnf"
  command: "/usr/bin/sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf"

# Redémmarer MariaDB
- name: "restart mariadb"
  service:
    name: "mariadb"
    state: restarted

